# Generated by Django 4.0.4 on 2022-05-30 06:45

import common.uploads
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('year', models.CharField(max_length=100, verbose_name='Datace')),
                ('technique', models.CharField(max_length=100, verbose_name='Technika')),
                ('collection', models.CharField(default='', max_length=200, verbose_name='Sbírka')),
                ('number', models.CharField(default='', max_length=50, verbose_name='Číslo')),
                ('notes', models.TextField(default='', verbose_name='Poznámky')),
                ('width', models.IntegerField(editable=False, verbose_name='Šířka repre obrazu')),
                ('height', models.IntegerField(editable=False, verbose_name='Výška repre obrazu')),
                ('file', models.ImageField(height_field='height', help_text='PNG soubor, 720px na vysku, sirka jak vyjde', max_length=255, upload_to=common.uploads.UploadPath('pictures'), verbose_name='Reprezentační obraz', width_field='width')),
                ('mask', models.ImageField(help_text='PNG soubor s výřezem pro tvář, rozměr 1280x720 pixelů', max_length=255, upload_to=common.uploads.UploadPath('masks'), verbose_name='Maska')),
            ],
            options={
                'verbose_name': 'Obraz',
                'verbose_name_plural': 'Obrazy',
                'ordering': ['title'],
            },
        ),
    ]
