# Generated by Django 4.0.4 on 2022-05-30 06:45

import common.uploads
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accompaniments', '0001_initial'),
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('raw_footage', models.FileField(blank=True, default='', upload_to=common.uploads.UploadPath('raw'), verbose_name='Hrubá nahrávka')),
                ('processed_footage', models.FileField(blank=True, default='', upload_to=common.uploads.UploadPath('processed'), verbose_name='Zprocesovaná nahrávka')),
                ('processed_stdout', models.TextField(blank=True, default='', editable=False, verbose_name='Processing STDOUT')),
                ('processed_stderr', models.TextField(blank=True, default='', editable=False, verbose_name='Processing STDERR')),
                ('processed_returncode', models.IntegerField(default=None, editable=False, null=True, verbose_name='Processing return code')),
                ('state', models.CharField(choices=[('initial', '(1/4) Výchozí'), ('raw', '(2/4) Hrubá nahrávka'), ('ready', '(3/4) Připraveno'), ('demonstrated', '(4/4) Odprezentováno'), ('error', 'Chyba')], default='initial', editable=False, max_length=20, verbose_name='Stav')),
                ('demonstrated_date', models.DateTimeField(blank=True, null=True, verbose_name='Datum prezentace')),
                ('selected', models.BooleanField(default=False, verbose_name='Kandidát na projekci')),
                ('accompaniment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accompaniments.accompaniment', verbose_name='Doprovod')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.picture', verbose_name='Obraz')),
            ],
            options={
                'verbose_name': 'Vystoupení',
                'verbose_name_plural': 'Vystoupení',
                'ordering': ['-created'],
            },
        ),
    ]
